#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
export GPG_TTY=$(tty)

mkpythondir() {
  if [ -d "$(pwd)/$1" ]
  then
    echo Directory "$(pwd)/$1" already exists
  else
    mkdir "$1"
    cp ~/python-boilerplate/* "$1"
    cp ~/python-boilerplate/.* "$1"
  fi
}
alias update='sudo apt update; sudo apt upgrade -y; sudo apt autoremove -y; sudo apt autoclean -y'