#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
export GPG_TTY=$(tty)

mkpythondir() {
  if [ ! -d "$(pwd)/$1" ]
  then
    rsync -r ~/git/python-boilerplate/ "$1" --exclude=".git"
    sed -i "" "s/PROJECT_NAME/$1/g" "$1/pyproject.toml"
  else
    echo "Directory $(pwd)/$1 already exists"
  fi
}

# pyenv tab completion
eval "$(pyenv init -)"

# Created by `pipx` on 2021-08-25 21:05:28
export PATH="$PATH:/Users/tailaiw/.local/bin"

# pipx tab completion
autoload -U bashcompinit
bashcompinit
eval "$(register-python-argcomplete pipx)"

# prezto tab completion
autoload -U compinit
compinit
